name: We Are Club
favicon: null
layout_spectrum: 0.5774558938574046
typography_spectrum: 0.80816
title: Voor een zorgeloos en verfrissend clubbeheer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42517f'
    - '#3094d1'
    - '#ffffff'
    - '#0080ff'
    - '#47a0d7'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.9863858299795538
purpose: []
